language: ruby
services:
  - docker
rvm:
  - 2.5
  - 2.6
before_install:
  - gem update --system
  - gem install bundler
  - docker-compose build
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
  - docker-compose run ruby_server bundle exec rake
  - bundle exec rubocop
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    recipients:
      - inferno@groups.mitre.org
    on_failure: change
