language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
script:
  - bundle exec rake
notifications:
  email:
    recipients:
      - fhir-testing-list@lists.mitre.org
    on_failure: change
before_install:
  - gem update --system
  - gem install bundler
