---
client_id:
  cerner: 04db5cb1-70e6-4200-8e9e-e12476b882a1
  epic: 6c12dff4-24e7-4475-a742-b08972c4ea27
  crucibledstu2: 7f872385-82bf-42cc-ac55-42d044235bbc #hspc
  cruciblestu3: 31ed51dd-dc4e-45d3-8002-4bfefdab5806 #hspc
  smart: 00000000-0000-0000-0000-000000000000
  mitre: test-test-test
scopes:
  cerner: online_access launch openid profile patient/AllergyIntolerance.read patient/Appointment.read
    patient/Condition.read patient/Contract.read patient/Device.read patient/DiagnosticReport.read
    patient/Encounter.read patient/Immunization.read patient/MedicationOrder.read
    patient/MedicationStatement.read patient/Observation.read patient/Patient.read
    patient/Person.read patient/RelatedPerson.read
  epic: launch openid profile patient/*.read
  crucibledstu2: launch patient/*.read openid profile #hspc
  cruciblestu3: launch patient/*.read openid profile #hspc
  smart: launch openid profile patient/*.read
  mitre: launch openid profile patient/*.read
base_url: ''
redirect_url: 'http://localhost:4567/app'
