version: '3'
services:
  ruby_server:
    build:
      context: ./
    volumes:
      - ./config.yml:/var/www/inferno/config.yml
    ports:
     - "4567:4567"
  bdt_service:
    image: infernocommunity/inferno-bdt-service
    ports:
     - "4500:4500"
